# Do not modify this file!  It was generated by ‘nixos-generate-config’
# and may be overwritten by future invocations.  Please make changes
# to /etc/nixos/configuration.nix instead.
{ config, lib, pkgs, modulesPath, ... }:

{
  imports =
    [ (modulesPath + "/installer/scan/not-detected.nix")
    ];

  boot.initrd.availableKernelModules = [ "xhci_pci" "ahci" "usb_storage" "sd_mod" "rtsx_usb_sdmmc" ];
  boot.initrd.kernelModules = [ ];
  boot.kernelModules = [ "kvm-intel" ];
  boot.extraModulePackages = [ ];

  fileSystems."/" =
    { device = "none";
      fsType = "tmpfs";
    };

  fileSystems."/boot" =
    { device = "/dev/disk/by-uuid/730C-8340";
      fsType = "vfat";
      options = [ "fmask=0077" "dmask=0077" ];
    };

  fileSystems."/nix" =
    { device = "/dev/disk/by-uuid/c2fa6280-367f-46eb-85aa-9ffcc2204e84";
      fsType = "ext4";
    };

  fileSystems."/persist/system" =
    { device = "/dev/disk/by-uuid/f4b95452-cddd-47b6-a6f2-490de33f0a6e";
      fsType = "ext4";
    };

  fileSystems."/persist/storage" =
    { device = "/dev/disk/by-uuid/2a828277-020f-4b76-9cc5-4bef985b00e5";
      fsType = "ext4";
    };

  fileSystems."/etc/nixos" =
    { device = "/persist/system/etc/nixos";
      fsType = "none";
      options = [ "bind" ];
    };

  fileSystems."/etc/credentials" =
    { device = "/persist/system/etc/credentials";
      fsType = "none";
      options = [ "bind" ];
    };

  swapDevices =
    [ { device = "/dev/disk/by-uuid/af38f7f7-b74f-478a-b107-4e6561ec415f"; }
    ];

  # Enables DHCP on each ethernet and wireless interface. In case of scripted networking
  # (the default) this is the recommended approach. When using systemd-networkd it's
  # still possible to use this option, but it's recommended to use it in conjunction
  # with explicit per-interface declarations with `networking.interfaces.<interface>.useDHCP`.
  networking.useDHCP = lib.mkDefault true;
  # networking.interfaces.wlo1.useDHCP = lib.mkDefault true;

  nixpkgs.hostPlatform = lib.mkDefault "x86_64-linux";
  hardware.cpu.intel.updateMicrocode = lib.mkDefault config.hardware.enableRedistributableFirmware;
}
