{...}: {
  imports = [
    ./allow-unfree.nix
    ./samba.nix
    ./autofs.nix
    ./users.nix
    ./kdeconnect.nix
    ./qtile.nix
    ./binsh-dash.nix
    ./audio.nix
    ./networking.nix
    ./doas.nix
    ./ntp.nix
    ./no-default-packages.nix
    ./git-daemon.nix
    ./dbus-broker.nix
    ./fonts.nix
    ./systemd-boot.nix
    ./offline-rebuild.nix
    ./sysrq.nix
    ./vivaldi.nix
    ./ssh.nix
    ./mako.nix
    ./wireshark.nix
    ./net-snmp.nix
    ./sway.nix
    ./ignore-power-keys.nix
    ./cifs-utils.nix
    ./lib.nix
    ./libreoffice.nix
    ./python.nix
    ./qbittorrent.nix
    ./sbcl.nix
    ./sshd.nix
    ./wtf.nix
    ./screenshot.nix
    ./unfree-fonts.nix
    ./wine.nix
  ];
}
