{...}: {
  imports = [
    ./allow-unfree.nix
    ./samba.nix
    ./autofs.nix
    ./users.nix
    ./kdeconnect.nix
    ./gnupg.nix
    ./qtile.nix
    ./binsh-dash.nix
    ./tmux.nix
    ./audio.nix
    ./networking.nix
    ./doas.nix
    ./ntp.nix
    ./no-default-packages.nix
    ./git-daemon.nix
    ./neovim.nix
    ./dbus-broker.nix
    ./fonts.nix
    ./systemd-boot.nix
    ./fish.nix
    ./offline-rebuild.nix
    ./sysrq.nix
    ./vivaldi.nix
    ./ssh.nix
    ./mako.nix
    ./wireshark.nix
    ./net-snmp.nix
    ./sway.nix
    ./ignore-power-keys.nix
    ./htop.nix
    ./cava.nix
    ./cifs-utils.nix
    ./endgame-singularity.nix
    ./lib.nix
    ./libreoffice.nix
    ./python.nix
    ./qbittorrent.nix
    ./sbcl.nix
    ./sshd.nix
    ./tor-browser.nix
    ./unp.nix
    ./wezterm.nix
    ./wtf.nix
    ./zoxide.nix
    ./git.nix
    ./screenshot.nix
    ./unfree-fonts.nix
    ./wine.nix
    ./pass.nix
  ];
}
